CREATE TABLE IF NOT EXISTS book
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(255),
    description character varying(255),
    price real,
    status_book integer NOT NULL,
    title character varying(255),
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS client
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rentalbooks
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(255),
    date_end_rental timestamp without time zone,
    date_start_rental timestamp without time zone,
    id_book integer NOT NULL,
    id_client integer NOT NULL,
    id_status_rental integer NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rentalbooks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS status_book
(
    id integer NOT NULL,
    status_book character varying(255),
    CONSTRAINT status_book_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS status_rental
(
    id integer,
    status_name character varying(255)
);

